server:
  port: 5000
spring:
  jpa:
    defer-datasource-initialization: true
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
    username: ${rds.username}
    password: ${rds.password}
  servlet:
    multipart:
      max-file-size: 20MB #최대 파일 사이즈 20MB로 지정
cloud:
  aws:
    credentials:
      accessKey: AKIAVFKKDIDCKVUMKXNH
      secretKey: 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
    s3:
      bucket: hsap-bucket
      dir: /receipt
    region:
      static: ap-northeast-2
    stack:
      auto: false
